# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxScore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=200)),
                ('team_2', models.CharField(max_length=200)),
                ('t1_q1', models.IntegerField()),
                ('t1_q2', models.IntegerField()),
                ('t1_q3', models.IntegerField()),
                ('t1_q4', models.IntegerField()),
                ('t2_q1', models.IntegerField()),
                ('t2_q2', models.IntegerField()),
                ('t2_q3', models.IntegerField()),
                ('t2_q4', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BoxScore',
        ),
    ]
