# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxScore', '0002_auto_20161030_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterscore',
            name='t1_total',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterscore',
            name='t2_total',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
