# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxScore', '0003_auto_20161030_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterscore',
            name='id',
        ),
        migrations.AddField(
            model_name='quarterscore',
            name='game_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 10, 0, 33, 0, 899911)),
        ),
        migrations.AddField(
            model_name='quarterscore',
            name='game_id',
            field=models.IntegerField(default=1111111, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
