# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxScore', '0005_auto_20161111_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterscore',
            name='game_date',
            field=models.DateField(blank=True),
        ),
    ]
